# **SET**

Set is an unordered collection of unique items. Set is defined by values separated by comma inside braces {}

In [2]:
# How to define
st=set()
print(type(st))

<class 'set'>

In [3]:
st={1,2,3}  #to pass values in a set, use curly brackets
print(type(st))

<class 'set'>

In [4]:
# whether support heterogeneous data or not
s={1,2,4.5,'sharon',True}   # print only either 1 or True and either 0 or False
print(s)

#support heterogeneous values

{1, 2, 4.5, 'sharon'}

In [5]:
s={2,4.5,'sharon',5,8.9,True}
print(s)
# Insertion order is not preserved

{True, 2, 4.5, 5, 8.9, 'sharon'}

In [6]:
# allow duplicate values or not
st={1,1,6,6,7,8,4,4,'sharon'}
print(st)
# duplicate values are not allowed

{1, 4, 6, 7, 8, 'sharon'}

In [7]:
#mutable or immutable
st={10,20,30,40,50,60}
print(st[0]) #indexing is not possible

TypeError: ignored

Even though indexing is not possible, Python sets are mutable because the set itself may be modified, but the elements contained in the set must be of an immutable type.

In [9]:

st.st={10,20,30,40,50,60}
st.add(90) # add element into a set
print(st)

AttributeError: ignored

In [10]:
st={10,20,30,40,50,60}
st.update([18,19,56]) # update is used to add multiple elements
print(st)

{40, 10, 50, 18, 20, 19, 56, 60, 30}

In [ ]:
st.st={10,20,30,40,50,60}
st.add(10) # we can not add 10 in the set because 10 is already in the set. Duplicates are not allowed.

AttributeError: ignored

In [ ]:
st1={100,200,300,400,500,600}
st1.remove(100) #remove the value 100
print(st1)

{200, 300, 400, 500, 600}

In [ ]:
st1={100,200,300,400,500,600}
st1.remove(700) # if the item is not in the set, the remove() function raises an error
print(st1)

KeyError: ignored

In [ ]:
st2={100,200,300,400,500,600}
st2.discard(100) #The discard () function does the same job as the remove() function.
print(st2)

{200, 300, 400, 500, 600}

In [ ]:
st2={100,200,300,400,500,600}
st2.discard(101) # If we are using discard() instead of remove(),even though the element is not in the set, it will not raise an error. 
print(st2)

{100, 200, 300, 400, 500, 600}

In [ ]:
s1={1,2,3,4,5,6,7,8,9,10}
print("Length=",len(s1))
print("Maximum of elements",max(s1))
print("Maximum of elements",min(s1))

Length= 10
Maximum of elements 10
Maximum of elements 1

In [ ]:

s2={10,20,30}
print("Sum =",sum(s2))

Sum = 60

In [ ]:
# Q. Suppose s2={10,20,30}. Find the sum of the set s2. 
#The element 10 is added to the set s2. What will be the new sum and why?

#Ans. Sum=60. The sum remains the same after the element 10 is added because duplicates are not allowed.

s2={10,20,30}
print("Sum =",sum(s2))
s2.add(10)
print("New sum=",sum(s2))

Sum = 60
New sum= 60

In [ ]:
s3={10,20,30}
print("Sum =",sum(s3))
s3.add(40)
print("New sum=",sum(s3))

Sum = 60
New sum= 100

In [ ]:
# Q. Consider the list lst=[10,10,20,40,70,60,60,60]. Remove the duplicates from the list.
# covert the list into a set using set() function because set dont allow duplicate values. Then convert again into a list

lst=[10,10,20,40,70,60,60,60]
st=set(lst)
print(st)
l=list(st)
print(l)

{70, 40, 10, 20, 60}
[70, 40, 10, 20, 60]